
package co.edu.udea.MelodyRabbit.GUI;

import java.awt.Color;
import java.awt.Dimension;
import java.util.Timer;
import java.util.TimerTask;

/**
 *
 * @author Luisa
 */
public class GUI extends javax.swing.JFrame {

    /**
     * Creates new form Bienvenida
     */
    boolean creditos = false;
    public GUI() {
        initComponents();
        this.setLocationRelativeTo(null); // CENTRA EL SEGUNDO FRAME EN LA PANTA 
        jLabel3.setVisible(false);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel3 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        btnAceptar = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        btnAceptar1 = new javax.swing.JButton();

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel3.setText("<html>Jeison Triana Amaya<br><br>Luisa Fernanda Suarez<br><br>Julian Trujillo Gallego<br><br>Pablo Tabares Castellanos</html>");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        jLabel2.setFont(new java.awt.Font("Century Schoolbook", 1, 24)); // NOI18N
        jLabel2.setText("Instrucciones");

        btnAceptar.setFont(new java.awt.Font("Century Schoolbook", 0, 18)); // NOI18N
        btnAceptar.setText("Aceptar");
        btnAceptar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAceptarActionPerformed(evt);
            }
        });

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/co/edu/udea/MelodyRabbit/GUI/image/InstruccionesSizePausa.png"))); // NOI18N
        jLabel1.setText("jLabel1");
        jLabel1.setPreferredSize(new java.awt.Dimension(622, 441));

        btnAceptar1.setFont(new java.awt.Font("Century Schoolbook", 0, 18)); // NOI18N
        btnAceptar1.setText("Creditos");
        btnAceptar1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAceptar1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(btnAceptar1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnAceptar))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 21, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnAceptar)
                    .addComponent(btnAceptar1))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnAceptarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAceptarActionPerformed
        // TODO add your handling code here:
        Menu m = Menu.getInstance();
        m.setLocationRelativeTo(null); // CENTRA EL SEGUNDO FRAME EN LA PANTA 
        m.setVisible(true);
        
        this.setVisible(false);
    }//GEN-LAST:event_btnAceptarActionPerformed

    private void btnAceptar1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAceptar1ActionPerformed
        
        if (!creditos) {
            creditos = true;
            btnAceptar.setVisible(false);
            btnAceptar1.setText("Volver");
            jLabel1.setVisible(false);
            jLabel2.setText("Creditos");
            jLabel3.setVisible(true);
            jLabel3.setSize(642, 1000);
            jLabel3.setLocation(100, 400);
            jLabel3.setText("<html><DIV ALIGN=CENTER>Jeison Triana Amaya<br><br>Luisa Fernanda Suarez<br><br>Julian Trujillo Gallego<br><br>Pablo Tabares Castellanos<br><br><br><br>Para analisis y diseño de sistemas II<br><br>Profesora:<br><br>Luz Viviana Cobaleda<br><br><br><br>Universidad de Antioquia<br><br>Medellín<br><br>2014</DIV></html>");
            this.add(jLabel3);



            Timer timer = new Timer();


            final TimerTask task = new TimerTask() {

                int x = -1;

                @Override
                public void run() {
                    if (jLabel3.getLocation().x >= 130) {
                        x = -1;
                    }
                    if (jLabel3.getLocation().x <= 70) {
                        x = 1;
                    }
                    jLabel3.setLocation(jLabel3.getLocation().x + x, jLabel3.getLocation().y - 4);
                }
            };

            timer.schedule(task, 0, 40);

        }
        else{
            creditos = false;
            btnAceptar.setVisible(true);
            btnAceptar1.setText("Creditos");
            jLabel1.setVisible(true);
            jLabel2.setText("instrucciones");
            jLabel3.setVisible(false);
            
            
        }
    }//GEN-LAST:event_btnAceptar1ActionPerformed


    /**
     * @param args the command line arguments
     */
  

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAceptar;
    private javax.swing.JButton btnAceptar1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    // End of variables declaration//GEN-END:variables
}
