/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package co.edu.udea.MelodyRabbit.GUI;

import co.edu.udea.MelodyRabbit.Logica.Controlador;
import co.edu.udea.MelodyRabbit.Logica.Puntaje;
import co.edu.udea.MelodyRabbit.Logica.Jugador;
import co.edu.udea.MelodyRabbit.Logica.Juego;
import java.awt.Desktop;
import java.io.IOException;
import java.net.URI;
import java.net.URISyntaxException;
import java.net.URL;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author luisa
 */
public class Menu extends javax.swing.JFrame {
    
    private static Menu menu;
    private Controlador ctrl=new Controlador();
   // private Juego nivel = new Juego();
    private ClaseObserver observador=new ClaseObserver();
    private PausaMenu pausa = new PausaMenu(observador);
    private int nivelJuego;
    
    /**
     * Creates new form menu
     */
    public static Menu getInstance(){
        if(menu==null){
            menu=new Menu();
        }
        return menu;
    }

    private Menu() {
        initComponents();
        pausa.setVisible(false);
        pausa.setLocationRelativeTo(null);
        pausa.setAlwaysOnTop(true);
        observador.addObserver(pausa);
        setDefaultCloseOperation(javax.swing.JFrame.EXIT_ON_CLOSE);
        cbNivel.setModel(new javax.swing.DefaultComboBoxModel(new String[]{"Seleccione uno", "Facil", "Medio", "Dificil"}));
        //   cbCancion.setModel(new javax.swing.DefaultComboBoxModel(new String[]{nivel.getCancionesPorNivel(1)[0], nivel.getCancionesPorNivel(1)[1]}));
        //txtRecord.setText(Integer.toString(ctrl.juegoGetRecordPuntuacion()));
         
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    
    
    
    
    
    
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        btnContinuar = new javax.swing.JButton();
        btnSalir = new javax.swing.JButton();
        txtNombre = new javax.swing.JTextField();
        cbNivel = new javax.swing.JComboBox();
        cbCancion = new javax.swing.JComboBox();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        jLabel1.setFont(new java.awt.Font("Century Schoolbook", 1, 18)); // NOI18N
        jLabel1.setText("Nombre:");

        jLabel2.setFont(new java.awt.Font("Century Schoolbook", 1, 18)); // NOI18N
        jLabel2.setText("Nivel:");

        jLabel3.setFont(new java.awt.Font("Century Schoolbook", 1, 18)); // NOI18N
        jLabel3.setText("Cancion:");

        btnContinuar.setFont(new java.awt.Font("Century Schoolbook", 1, 18)); // NOI18N
        btnContinuar.setText("Continuar");
        btnContinuar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnContinuarActionPerformed(evt);
            }
        });

        btnSalir.setFont(new java.awt.Font("Century Schoolbook", 1, 18)); // NOI18N
        btnSalir.setText("Salir");
        btnSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalirActionPerformed(evt);
            }
        });

        txtNombre.setFont(new java.awt.Font("Century Schoolbook", 0, 18)); // NOI18N

        cbNivel.setFont(new java.awt.Font("Century Schoolbook", 0, 18)); // NOI18N
        cbNivel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbNivelActionPerformed(evt);
            }
        });

        cbCancion.setFont(new java.awt.Font("Century Schoolbook", 0, 18)); // NOI18N
        cbCancion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbCancionActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(cbCancion, javax.swing.GroupLayout.PREFERRED_SIZE, 191, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel1)
                                    .addComponent(jLabel2))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(txtNombre)
                                    .addComponent(cbNivel, 0, 194, Short.MAX_VALUE)))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btnSalir)
                                .addGap(18, 18, 18)
                                .addComponent(btnContinuar)))
                        .addGap(22, 22, 22))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(cbNivel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(cbCancion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnSalir)
                    .addComponent(btnContinuar))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnContinuarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnContinuarActionPerformed
        // TODO add your handling code here:
        int n = this.cbNivel.getSelectedIndex();
        int c = this.cbCancion.getSelectedIndex();

        if (txtNombre.getText().isEmpty()|| n == 0) {
            JOptionPane.showMessageDialog(null, "Debe ingresar un nombre");
        } else {
         //   Jugador jugador = new Jugador();
           ctrl.jugadorSetNombre(txtNombre.getText());
            String url = ctrl.juegoGetCancion(c).getUrl();

            if (Desktop.isDesktopSupported()) {
                try {
                    try {
                        Desktop.getDesktop().browse(new URI(url));
                    } catch (URISyntaxException ex) {
                        Logger.getLogger(Menu.class.getName()).log(Level.SEVERE, null, ex);
                    }
                } catch (IOException ex) {
                    Logger.getLogger(Menu.class.getName()).log(Level.SEVERE, null, ex);
                }
            } else {
                // Ubuntu
                Runtime runtime = Runtime.getRuntime();
                try {
                    runtime.exec("/usr/bin/firefox -new-window " + url);
                } catch (IOException ex) {
                    Logger.getLogger(Menu.class.getName()).log(Level.SEVERE, null, ex);
                }
            }

              MelodyRabbit mr = new MelodyRabbit(ctrl,  nivelJuego , observador, txtNombre.getText(), c);
            mr.setLocationRelativeTo(null); // CENTRA EL SEGUNDO FRAME EN LA PANTA 
            mr.setVisible(true);
            mr.setAlwaysOnTop(true);
            
            observador.addObserver(mr);
            this.setVisible(false);
            //Juego juego = new Juego();
            //juego.setNivel(nivelJuego);
        }


    }//GEN-LAST:event_btnContinuarActionPerformed
    
    private void btnSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalirActionPerformed
        // TODO add your handling code here:
        System.exit(0);
        this.setVisible(false);
        this.dispose();
    }//GEN-LAST:event_btnSalirActionPerformed

    private void cbNivelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbNivelActionPerformed
        // TODO add your handling code here:
        int n = this.cbNivel.getSelectedIndex();
        switch (n) {
            case 0:
                JOptionPane.showMessageDialog(null, "Debe seleccionar un nivel");
                break;

            case 1:
                ctrl.juegoNivel1();
                ctrl.juegoConstruir();
                nivelJuego = 1;
                cbCancion.setModel(new javax.swing.DefaultComboBoxModel(new String[]{ctrl.juegoGetCancion(0).getNombre(), ctrl.juegoGetCancion(1).getNombre()}));

                break;

            case 2:
                ctrl.juegoNivel2();
                ctrl.juegoConstruir();
                nivelJuego = 2;
                cbCancion.setModel(new javax.swing.DefaultComboBoxModel(new String[]{ctrl.juegoGetCancion(0).getNombre(), ctrl.juegoGetCancion(1).getNombre()}));

                break;

            case 3:
                ctrl.juegoNivel3();
                ctrl.juegoConstruir();
                nivelJuego = 3;
                cbCancion.setModel(new javax.swing.DefaultComboBoxModel(new String[]{ctrl.juegoGetCancion(0).getNombre(), ctrl.juegoGetCancion(1).getNombre()}));

                break;

        }
        
        
      //  nivel.getCancionesPorNivel();
        // cbCancion.setModel(new javax.swing.DefaultComboBoxModel(new String[]{nivel.getCancionesPorNivel()[0], nivel.getCancionesPorNivel(n)[1]}));
//        txtRecord.setText(Integer.toString(ctrl.juegoGetRecordPuntuacion()));


    }//GEN-LAST:event_cbNivelActionPerformed

    private void cbCancionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbCancionActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbCancionActionPerformed

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnContinuar;
    private javax.swing.JButton btnSalir;
    private javax.swing.JComboBox cbCancion;
    private javax.swing.JComboBox cbNivel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JTextField txtNombre;
    // End of variables declaration//GEN-END:variables
}
