/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package co.edu.udea.MelodyRabbit.GUI;

/**
 *
 * @author Jeison
 */
public class Partida extends javax.swing.JPanel {

    /**
     * Creates new form Partida
     */
    public Partida() {
        initComponents();
        this.setOpaque(false);
    }

    
    public void setNombre(String s){
        nombre.setText(s);
    }
    
    public void setEscala(String s, boolean m) {
        escala.setText("Escala: " + s);

        if (!m) {
            escala.setText("Escala: " + s + "m");
        }
    }

    public void setBpm(int b) {
        bpm.setText("Velocidad: " + Integer.toString(b));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        bpm = new javax.swing.JLabel();
        nombre = new javax.swing.JLabel();
        escala = new javax.swing.JLabel();

        bpm.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        bpm.setForeground(new java.awt.Color(255, 255, 255));
        bpm.setText("Bpm");

        nombre.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        nombre.setForeground(new java.awt.Color(255, 255, 255));
        nombre.setText("Nombre");

        escala.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        escala.setForeground(new java.awt.Color(255, 255, 255));
        escala.setText("Escala");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(96, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(nombre, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(bpm, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(escala, javax.swing.GroupLayout.Alignment.TRAILING))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(4, 4, 4)
                .addComponent(nombre)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(escala)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(bpm)
                .addContainerGap(17, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel bpm;
    private javax.swing.JLabel escala;
    private javax.swing.JLabel nombre;
    // End of variables declaration//GEN-END:variables
}
